apiVersion: v1
kind: Service
metadata:
  name: libraryserviceservice
spec:
  type: NodePort
  selector:
    app: libraryservice
  ports:
    - protocol: TCP
      nodePort: 30081
      port: 9003
      targetPort: 9003